fix: add variable assignment checking as part of MinVersion
securego/gosec pull request #669
Opened 2021-07-19 13:21 UTC by nanikjava

Fix for #528

This PR update the assignment checking for `MinVersion` of TLS

2021-07-20 20:57 UTC, ccojocar commented on rules/tls.go
> +						fmt.Println(x, sel)
The `Println` should be removed before merging.

2021-07-20 20:59 UTC, ccojocar commented on rules/tls.go
> +								fmt.Print(cnst.Val().String())
ditto

2021-07-20 21:00 UTC, ccojocar requested changes
Please could you also try to fix the lint warning. I think not all all related to your changes. Thanks

2021-07-25 05:05 UTC, nanikjava commented
@ccojocar Done all the changes you request and added test cases.

2021-07-27 20:03 UTC, ccojocar approved these changes
Thanks @nanikjava for fixing my comments!

2021-07-27 20:03 UTC, merged