adds -convert flag which writes output to two files:
securego/gosec pull request #814
Opened 2022-05-16 19:48 UTC by ArnPellesGit

json and any of the other valid formats. Also edited README to reflect this change. 
Partially fixes #598

2022-05-16 19:49 UTC, ArnPellesGit commented on README.md
> +Results will be reported to stdout as well as to the provided output file by `-stdout` flag. The `-verbose` flag overrides the
This change was made by my editor. Should I fix this or is this fine?

2022-05-16 19:50 UTC, ArnPellesGit commented on README.md
> +The released artifacts are signed using [cosign](https://docs.sigstore.dev/). You can use the public key from [cosign.pub](cosign.pub)
see above comment

2022-05-16 19:51 UTC, ArnPellesGit commented on README.md
> +
see above comment

2022-06-01 15:30 UTC, ccojocar requested changes

2022-06-01 15:30 UTC, ccojocar commented on README.md
> +$ gosec -fmt=json -out=log.json -convert=text,log.txt ./...
I am not sure if this is the most descriptive way to do this. I would rather allow multiple formats something like:

```
gosec -fmt=json,text -out=log ./...
```
and attached the file extensions according with the format

2022-06-01 15:30 UTC, ccojocar commented on README.md
> +$ gosec -fmt=json -out=log.json -convert=text,log.txt ./...
I am not sure if this is the most descriptive way to do this. I would rather allow multiple formats something like:

```
gosec -fmt=json,text -out=log ./...
```
and attached the file extensions according with the format

2022-06-01 15:30 UTC, ccojocar commented on README.md
> +The released artifacts are signed using [cosign](https://docs.sigstore.dev/). You can use the public key from [cosign.pub](cosign.pub)
This is fine.

2022-06-01 15:30 UTC, ccojocar commented on README.md
> +The released artifacts are signed using [cosign](https://docs.sigstore.dev/). You can use the public key from [cosign.pub](cosign.pub)
This is fine.

2022-06-01 15:30 UTC, ccojocar commented on README.md
> +
please remove this line

2022-06-23 12:44 UTC, ccojocar commented
Closing this due to the lack of inactivity. Thanks

2022-06-23 12:44 UTC, closed without merging